### ISSUE TITLE
Dynamic component

### ISSUE THREAD

**Issue by jrmessias** [secondnetwork/blade-tabler-icons#1]
Hi,
I am use icons from database for modules at my system, i need show the icons dinamycally from a loop.

I tried use dynamic components but not sucessfull.

```
$icon = "x-tabler-lock"
<x-dynamic-component :component="$icon" />
```

Did you have a suggestion for this situation?

**Comment by secondnetwork** [comment]
Hi,
Try the solution, use @svg
```
@php
    $icon = "tabler-lock"
@endphp

@svg($icon, 'w-6 h-6')
```

**Comment by secondnetwork** [comment]
Hi
The question is, does it show the same missing with the normal method?
```
<x-tabler-lock class="w-6 h-6" />
```
remove the **x-**
```
@svg('tabler-lock', 'w-6 h-6')
```
have you tried that?
```
php artisan vendor:publish --tag=blade-icons --force
```

**Comment by jrmessias** [comment]
Hi @secondnetwork 

Sorry, my inattention, I remove the 'x-' and work with @svg().

I don't use 'php artisan' command.

Thanks for help
