### ISSUE TITLE
New structure filled/outline

### ISSUE THREAD

**Issue by divdax** [secondnetwork/blade-tabler-icons#57]
The latest Tabler Icon Release removed `circle-check-filled` and replaced it with `circle-check` for filled icons. To get the filled version, use `<x-tabler-circle-check>`. If you need the outlined version of `circle-check`, how can you request it?

using v2.4.8

**Comment by secondnetwork** [comment]
The filled icons can be referenced like this:

<x-tabler-alert-circle-r />

**Comment by secondnetwork** [comment]
Good idea,
in the new version 3.0.5 add suffix for filled icons

The filled icons can be referenced like this:

```blade
<x-tabler-alert-circle-filled />
```
Or
```blade
<x-tabler-alert-circle-f />

```
